# yaml-language-server: $schema=../schema/ankiday-config.schema.json
version: 1
backend: ankiConnect
server:
  url: http://127.0.0.1:8765
  timeoutSeconds: 30
prune:
  decks: false
  models: false
  notes: false

models:
  - name: BasicExt
    css: |
      .card {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif;
        font-size: 20px;
        text-align: left;
      }
    fields: [Front, Back, Extra]
    templates:
      - name: Card 1
        qfmt: "{{Front}}"
        afmt: "{{Front}}<hr id=answer>{{Back}}<div class=extra>{{Extra}}</div>"
    uniqueField: Front

decks:
  - name: Languages::Spanish
    config: {}

notes:
  - model: BasicExt
    deck: Languages::Spanish
    fields:
      Front: "hola"
      Back: "hello"
      Extra: "greeting"
    tags: [spanish, greeting]
  - model: BasicExt
    deck: Languages::Spanish
    fields:
      Front: "adiós"
      Back: "goodbye"
    tags: [spanish]